### ISSUE TITLE
about table issue

### ISSUE THREAD

**Issue by alphime** [Yazan98/MarkdownCompose#1]
If the text has multiple code blocks, there will be a issue that the contents of these code blocks will be exactly the same， then I tried to fix it. As shown in the following figure ...
![image](https://github.com/Yazan98/Markdown-Compose/assets/109449075/d3e957e7-2b6e-4a0f-a548-046394438eed)

then I found the function of table hasn't realized it yet. I hope you can achieve the basic functions. And thank you for the source code.

**Comment by Yazan98** [comment]
@alphime Hello alphime
Sorry for late
Thank you for reporting the bug and now i published the fix in version 1.0.4 of the library
